version: "3.3"
services:
  # redisdb:
  #   image: redis
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redisData:/data
  postgresql:
    image: postgres
    environment:
      POSTGRES_DB: bruh
      POSTGRES_USER: bruh-user
      POSTGRES_PASSWORD: BruhReally
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./pg/pg-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
